version: 3.0.{build}
branches:
  only:
  - master
  - dev
image: Visual Studio 2017
init:
- cmd: git config --global core.autocrlf true
install:
- ps: >-
    $env:BuildNumber= $env:APPVEYOR_BUILD_NUMBER

    $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = true

    $env:NUGET_XMLDOC_MODE = "skip"

    $env:DOTNET_CLI_TELEMETRY_OPTOUT = 1
cache: tools
nuget:
  disable_publish_on_pr: true
build_script:
- ps: >-
    dotnet --version

    dotnet restore

    dotnet build -c Release

    dotnet pack -c Release
test: off
